In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from sklearn import linear_model
%matplotlib inline

/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


# Credit data

In [2]:
data = pd.read_csv('http://www-bcf.usc.edu/~gareth/ISL/Credit.csv', index_col=0)

In [3]:
data.head()

Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
1   14.891   3606     283      2   34         11    Male      No     Yes   
2  106.025   6645     483      3   82         15  Female     Yes     Yes   
3  104.593   7075     514      4   71         11    Male      No      No   
4  148.924   9504     681      3   36         11  Female      No      No   
5   55.882   4897     357      2   68         16    Male      No     Yes   

   Ethnicity  Balance  
1  Caucasian      333  
2      Asian      903  
3      Asian      580  
4      Asian      964  
5  Caucasian      331

In [4]:
data.tail()

Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
396  12.096   4100     307      3   32         13    Male      No     Yes   
397  13.364   3838     296      5   65         17    Male      No      No   
398  57.872   4171     321      5   67         12  Female      No     Yes   
399  37.728   2525     192      1   44         13    Male      No     Yes   
400  18.701   5524     415      5   64          7  Female      No      No   

            Ethnicity  Balance  
396         Caucasian      560  
397  African American      480  
398         Caucasian      138  
399         Caucasian        0  
400             Asian      966

In [5]:
sns.pairplot(data, x_vars=['Income', 'Limit'], y_vars='Balance', size=7, aspect=0.7, kind='reg')

In [6]:
X=data[['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education']]
Y=data['Balance']

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=1)

In [8]:
#Lasso

In [9]:
clf = linear_model.Lasso(alpha=20)

In [10]:
clf.fit(X_train, Y_train)

Lasso(alpha=20, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [11]:
clf.coef_

array([-7.15253339,  0.05964496,  2.98617329,  0.        , -0.7694637 ,
        0.42999251])

In [12]:
clf.intercept_

-465.03609128782171

# scores

In [13]:
clf.score(X_test, Y_test)

0.86961251100594639

# cross validation

In [14]:
cross_val_score(clf, X, Y, cv=5)

array([ 0.8600418 ,  0.85456087,  0.88492109,  0.87161247,  0.88764481])

# rescaling 

In [15]:
scaler = preprocessing.StandardScaler().fit(X_test)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
print(scaler.mean_)
print(scaler.scale_)

[  5.02095500e+01   5.04940000e+03   3.75630000e+02   2.77000000e+00
   5.64300000e+01   1.32500000e+01]
[  3.87158186e+01   2.48453851e+03   1.63337176e+02   1.24783813e+00
   1.60619146e+01   3.15079355e+00]


In [17]:
print(np.mean(scaler.transform(X_test), axis=0))
print(np.std(scaler.transform(X_test), axis=0))

[  2.00950367e-16   1.46965773e-16   3.05311332e-17   1.94289029e-18
   1.47104551e-17   8.88178420e-18]
[ 1.  1.  1.  1.  1.  1.]


In [81]:
alphas = np.linspace(2,2000,1000)
clfs = np.array([])
betas = np.array([[0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0]])
for i in alphas:
    clf = linear_model.Lasso(alpha=i)
    clf.fit(X_train, Y_train)
    clfs = np.append(clfs,[clf.score(X_test,Y_test)])
    betas = np.append(betas,[clf.coef_],axis=0)

In [87]:
plt.plot(alphas,betas[2:,5])

In [73]:
print(betas.shape)

(102, 6)
